// AUTOTRANSPORTES ALANIS - Catalogo de fallas de unidades
// 263 fallas clasificadas por sistema y severidad
const FALLAS = [
  { id:1, cat:'Electrico y luces', name:'Revisar baterias', sev:'media' },
  { id:2, cat:'Emisiones (UREA/DEF/SCR)', name:'Revisar sistema de UREA', sev:'media' },
  { id:3, cat:'Motor', name:'Perdida de potencia', sev:'alta' },
  { id:4, cat:'Clima y refrigeracion', name:'Revisar minisplit', sev:'media' },
  { id:5, cat:'Llantas', name:'Cambio de llantas', sev:'alta' },
  { id:6, cat:'Emisiones (UREA/DEF/SCR)', name:'Revisar post enfriador', sev:'media' },
  { id:7, cat:'Transmision', name:'Revisar falla de transmisión', sev:'alta' },
  { id:8, cat:'Motor', name:'Consumo de diesel', sev:'media' },
  { id:9, cat:'Suspension', name:'Fuga de aire en suspensión', sev:'media' },
  { id:10, cat:'Transmision', name:'Cambio de reverseros', sev:'media' },
  { id:11, cat:'Transmision', name:'Revisar clutch', sev:'media' },
  { id:12, cat:'Transmision', name:'Engrasado de collarin', sev:'media' },
  { id:13, cat:'Clima y refrigeracion', name:'Revisar TRIPAC', sev:'media' },
  { id:14, cat:'Electrico y luces', name:'Revisar luces en general (interior y exterior)', sev:'media' },
  { id:15, cat:'Carroceria y cabina', name:'Cambiar soportes de cabina', sev:'baja' },
  { id:16, cat:'Llantas', name:'Cambio de llantas delanteras', sev:'alta' },
  { id:17, cat:'Clima y refrigeracion', name:'Poner gas a A/C', sev:'media' },
  { id:18, cat:'Motor', name:'Revisar marcha', sev:'alta' },
  { id:19, cat:'Emisiones (UREA/DEF/SCR)', name:'Servicio SCR (Regeneración)', sev:'media' },
  { id:20, cat:'Transmision', name:'Servicio a la transmisión GI', sev:'media' },
  { id:21, cat:'Direccion', name:'Cambiar palanca de direccionales', sev:'alta' },
  { id:22, cat:'Sensores y diagnostico', name:'Borrar códigos', sev:'media' },
  { id:23, cat:'Direccion', name:'Revisar dirección', sev:'alta' },
  { id:24, cat:'Transmision', name:'Revisar transmision', sev:'media' },
  { id:25, cat:'Motor', name:'Revisar bajo rendimiento', sev:'media' },
  { id:26, cat:'Motor', name:'Revisar consumos extra de combustible', sev:'media' },
  { id:27, cat:'Frenos', name:'Ajustar frenos', sev:'alta' },
  { id:28, cat:'Transmision', name:'Revisar fan clutch (se queda pegado)', sev:'media' },
  { id:29, cat:'Suspension', name:'Revisar suspensión trasera', sev:'media' },
  { id:30, cat:'Emisiones (UREA/DEF/SCR)', name:'Revisar humo de UREA', sev:'media' },
  { id:31, cat:'Suspension', name:'Reparar muelle lado izq', sev:'media' },
  { id:32, cat:'Transmision', name:'Revisar transmisión (se bloquea)', sev:'alta' },
  { id:33, cat:'Electrico y luces', name:'Ajustar baterias', sev:'media' },
  { id:34, cat:'Electrico y luces', name:'Luces delanteras bajas', sev:'media' },
  { id:35, cat:'Direccion', name:'Revisar depósito de aceite de la dirección', sev:'alta' },
  { id:36, cat:'Transmision', name:'Revisar transmisión (truena)', sev:'alta' },
  { id:37, cat:'Electrico y luces', name:'Cambio de luces delanteras', sev:'media' },
  { id:38, cat:'Combustible', name:'Enderezar tanque de diesel', sev:'media' },
  { id:39, cat:'Combustible', name:'Flotador de diesel', sev:'media' },
  { id:40, cat:'Clima y refrigeracion', name:'Reparación de mini Split', sev:'media' },
  { id:41, cat:'Suspension', name:'Cambio de bolsa de aire delantera lado izq', sev:'media' },
  { id:42, cat:'Carroceria y cabina', name:'Reparar alerón superior izq', sev:'baja' },
  { id:43, cat:'Suspension', name:'Cambio de barra estabilizadora', sev:'media' },
  { id:44, cat:'Electrico y luces', name:'Corto en intermitentes', sev:'media' },
  { id:45, cat:'Direccion', name:'Corto en direccional lado izq', sev:'alta' },
  { id:46, cat:'Emisiones (UREA/DEF/SCR)', name:'Mantenimiento a sistema DEF', sev:'media' },
  { id:47, cat:'General', name:'Revisar detalle en tanque', sev:'media' },
  { id:48, cat:'Clima y refrigeracion', name:'Revisar instalación de A/C', sev:'media' },
  { id:49, cat:'Transmision', name:'Se patina clutch', sev:'alta' },
  { id:50, cat:'Direccion', name:'Revisar baleros delanteros', sev:'alta' },
  { id:51, cat:'Emisiones (UREA/DEF/SCR)', name:'Cambio de defensa', sev:'media' },
  { id:52, cat:'Diferenciales y eje', name:'Cambiar hules de tirantes de diferenciales', sev:'media' },
  { id:53, cat:'Transmision', name:'Configurar paso de diferenciales a transmisión', sev:'media' },
  { id:54, cat:'Electrico y luces', name:'Revisar sistema electrico', sev:'media' },
  { id:55, cat:'Clima y refrigeracion', name:'Revisar refrigerador', sev:'media' },
  { id:56, cat:'Carroceria y cabina', name:'Reparación de escalón derecho', sev:'baja' },
  { id:57, cat:'Electrico y luces', name:'Faro lado derecho', sev:'media' },
  { id:58, cat:'Carroceria y cabina', name:'Cambiar soporte de fascia lado derecho', sev:'baja' },
  { id:59, cat:'Frenos', name:'Revisión y reparación de sistema de frenos', sev:'alta' },
  { id:60, cat:'Suspension', name:'Bujes de las muelles', sev:'media' },
  { id:61, cat:'Frenos', name:'Calibrar balatas', sev:'alta' },
  { id:62, cat:'Motor', name:'Poner a nivel aceite de motor', sev:'media' },
  { id:63, cat:'Mantenimiento general', name:'Cambio de aceite y filtros', sev:'media' },
  { id:64, cat:'Mantenimiento general', name:'Cambio de radiador', sev:'media' },
  { id:65, cat:'Llantas', name:'Revisar llanta delantera lado izq', sev:'alta' },
  { id:66, cat:'Sensores y diagnostico', name:'Configuración de parametros', sev:'media' },
  { id:67, cat:'Emisiones (UREA/DEF/SCR)', name:'Servicio al EGR', sev:'media' },
  { id:68, cat:'Frenos', name:'Cambiar manguera de rotachamber lado derecho', sev:'alta' },
  { id:69, cat:'Suspension', name:'Fuga en bolsas lado derecho', sev:'media' },
  { id:70, cat:'Suspension', name:'Fuga de aire en bolsas traseras', sev:'media' },
  { id:71, cat:'Motor', name:'Trabaja fuera de RPM', sev:'media' },
  { id:72, cat:'Transmision', name:'Ajustar parametros de la transmisión', sev:'media' },
  { id:73, cat:'Motor', name:'Revisar humo negro', sev:'media' },
  { id:74, cat:'Combustible', name:'Filtros de diesel', sev:'media' },
  { id:75, cat:'Mantenimiento general', name:'Fuga en sistema de admisión', sev:'media' },
  { id:76, cat:'Emisiones (UREA/DEF/SCR)', name:'Cambio de filtro de urea', sev:'media' },
  { id:77, cat:'Sensores y diagnostico', name:'Revisar código activo', sev:'media' },
  { id:78, cat:'Carroceria y cabina', name:'Reparación de faldones', sev:'baja' },
  { id:79, cat:'Motor', name:'No enciende-baterias', sev:'alta' },
  { id:80, cat:'Emisiones (UREA/DEF/SCR)', name:'Limpieza de válvula EGR', sev:'media' },
  { id:81, cat:'Transmision', name:'Cambiar reversero', sev:'media' },
  { id:82, cat:'Mantenimiento general', name:'Reapretada a tornillería en general', sev:'media' },
  { id:83, cat:'Clima y refrigeracion', name:'Cambiar radiador de clima', sev:'media' },
  { id:84, cat:'Mantenimiento general', name:'Enderezar radiador de camión', sev:'media' },
  { id:85, cat:'Clima y refrigeracion', name:'Servicio a a/c externo', sev:'media' },
  { id:86, cat:'Frenos', name:'Revisar falso contacto en freno de motor', sev:'alta' },
  { id:87, cat:'Motor', name:'Revisar cascabeleo en motor', sev:'media' },
  { id:88, cat:'Emisiones (UREA/DEF/SCR)', name:'Detallar defensa y cofre', sev:'media' },
  { id:89, cat:'Carroceria y cabina', name:'Ajustar porta placas', sev:'baja' },
  { id:90, cat:'Transmision', name:'Poner filtro seco original', sev:'media' },
  { id:91, cat:'Sistema de aire', name:'Fuga de aire en mangueras', sev:'alta' },
  { id:92, cat:'Sistema de aire', name:'Revisar fugas de aire', sev:'alta' },
  { id:93, cat:'Motor', name:'Revisar alternador', sev:'alta' },
  { id:94, cat:'Mantenimiento general', name:'Abrazaderas de admisión', sev:'media' },
  { id:95, cat:'Sensores y diagnostico', name:'Cambiar sensor de aire', sev:'media' },
  { id:96, cat:'Sensores y diagnostico', name:'Revisar códigos activos', sev:'media' },
  { id:97, cat:'Mantenimiento general', name:'Cambio de bujes', sev:'media' },
  { id:98, cat:'Emisiones (UREA/DEF/SCR)', name:'Limpieza de líneas de urea', sev:'media' },
  { id:99, cat:'Frenos', name:'Revisar matracas de frenado traseras', sev:'alta' },
  { id:100, cat:'Mantenimiento general', name:'Relleno de niveles', sev:'media' },
  { id:101, cat:'Motor', name:'Ruido al acelerar', sev:'media' },
  { id:102, cat:'Diferenciales y eje', name:'Colocar guías del chasis en el eje del inter', sev:'media' },
  { id:103, cat:'Carroceria y cabina', name:'Revisar asiento de operador', sev:'baja' },
  { id:104, cat:'Transmision', name:'Revisar clutch (se patina)', sev:'alta' },
  { id:105, cat:'Mantenimiento general', name:'Cambio die banda de accesorios', sev:'media' },
  { id:106, cat:'Transmision', name:'Engrasar transmisión', sev:'media' },
  { id:107, cat:'Transmision', name:'Desactivar fan clutch', sev:'media' },
  { id:108, cat:'Mantenimiento general', name:'Cambiar punta de tapas de punteria', sev:'media' },
  { id:109, cat:'Clima y refrigeracion', name:'Clima de cabina', sev:'media' },
  { id:110, cat:'Carroceria y cabina', name:'Cambio de tirante de cofre', sev:'baja' },
  { id:111, cat:'Carroceria y cabina', name:'Revisión de cofre', sev:'baja' },
  { id:112, cat:'Transmision', name:'Se neutraliza la transmisión', sev:'alta' },
  { id:113, cat:'Sistema de aire', name:'Línea de aire a fan clucth', sev:'alta' },
  { id:114, cat:'Transmision', name:'Banda de fan clutch', sev:'media' },
  { id:115, cat:'Suspension', name:'Calibrar bolsas de aire', sev:'media' },
  { id:116, cat:'Transmision', name:'Reverseros', sev:'media' },
  { id:117, cat:'Motor', name:'Revisar turbo', sev:'alta' },
  { id:118, cat:'Transmision', name:'Corregir fuga de aceite en masa delantera', sev:'media' },
  { id:119, cat:'Llantas', name:'Cambio de llantas dañadas', sev:'alta' },
  { id:120, cat:'Emisiones (UREA/DEF/SCR)', name:'Revisar olor a UREA', sev:'media' },
  { id:121, cat:'Electrico y luces', name:'Revisar luces delanteras', sev:'media' },
  { id:122, cat:'Electrico y luces', name:'Revisar intermitentes', sev:'media' },
  { id:123, cat:'Emisiones (UREA/DEF/SCR)', name:'Sensor NOX', sev:'media' },
  { id:124, cat:'Combustible', name:'Revisar bombas de diesel', sev:'media' },
  { id:125, cat:'Transmision', name:'Arreglar fan clutch', sev:'media' },
  { id:126, cat:'Suspension', name:'Cambiar amortiguadores delanteros', sev:'media' },
  { id:127, cat:'Frenos', name:'Fuga en valvula repartidora', sev:'alta' },
  { id:128, cat:'Transmision', name:'Código GI en engrane de la transmisión', sev:'media' },
  { id:129, cat:'Clima y refrigeracion', name:'Fuga de gas del A/C', sev:'media' },
  { id:130, cat:'Diferenciales y eje', name:'Calibrar bolsas de aire Eje delantero', sev:'media' },
  { id:131, cat:'General', name:'Lavar GR', sev:'media' },
  { id:132, cat:'Electrico y luces', name:'Faro', sev:'media' },
  { id:133, cat:'Sensores y diagnostico', name:'Cambiar sensor de presión de aceite', sev:'media' },
  { id:134, cat:'Suspension', name:'Cambiar válvula reguladora de bolsas traseras', sev:'media' },
  { id:135, cat:'Transmision', name:'Transmisión golpea', sev:'alta' },
  { id:136, cat:'Suspension', name:'Tensores de la suspensión', sev:'media' },
  { id:137, cat:'Carroceria y cabina', name:'Reparación de costado lado de chofer', sev:'baja' },
  { id:138, cat:'Transmision', name:'Cambiar sensor de fan clutch', sev:'media' },
  { id:139, cat:'Carroceria y cabina', name:'Cambiar percha de soporte de inter', sev:'baja' },
  { id:140, cat:'General', name:'Colocar guía de chasis', sev:'media' },
  { id:141, cat:'Transmision', name:'Revisar check engine', sev:'media' },
  { id:142, cat:'Emisiones (UREA/DEF/SCR)', name:'Post enfriador', sev:'media' },
  { id:143, cat:'Suspension', name:'Bolsas de suspension trasera', sev:'media' },
  { id:144, cat:'Suspension', name:'Válvulas de suspensión trasera', sev:'media' },
  { id:145, cat:'Clima y refrigeracion', name:'Cambiar compresor', sev:'media' },
  { id:146, cat:'Direccion', name:'Direccional lado izq', sev:'alta' },
  { id:147, cat:'Electrico y luces', name:'Colocar plafones', sev:'media' },
  { id:148, cat:'Electrico y luces', name:'Reforzar plafonera', sev:'media' },
  { id:149, cat:'Suspension', name:'Cambiar amortiguador 5 y 6', sev:'media' },
  { id:150, cat:'Suspension', name:'Abrazaderas de muelles delanteros lado izq', sev:'media' },
  { id:151, cat:'Suspension', name:'Bolsas de aire lado izq', sev:'media' },
  { id:152, cat:'Carroceria y cabina', name:'Arreglar fascia delantera', sev:'baja' },
  { id:153, cat:'Mantenimiento general', name:'Revisar niveles de aceite', sev:'media' },
  { id:154, cat:'Transmision', name:'Calibrar transmisión', sev:'media' },
  { id:155, cat:'Suspension', name:'Valvula de suspension derecha delantera', sev:'media' },
  { id:156, cat:'Electrico y luces', name:'Plafon lado izq trasero', sev:'media' },
  { id:157, cat:'Emisiones (UREA/DEF/SCR)', name:'Limpieza de catalizador', sev:'media' },
  { id:158, cat:'Electrico y luces', name:'Revisar faros principales', sev:'media' },
  { id:159, cat:'Electrico y luces', name:'Revisar cuartos traseros', sev:'media' },
  { id:160, cat:'Carroceria y cabina', name:'Cintos de seguridad', sev:'baja' },
  { id:161, cat:'Carroceria y cabina', name:'Apretar salpicadera', sev:'baja' },
  { id:162, cat:'Frenos', name:'Revisar falso en freno de motor', sev:'alta' },
  { id:163, cat:'Electrico y luces', name:'Falla en intermitentes', sev:'media' },
  { id:164, cat:'Electrico y luces', name:'Revisar luces laterales', sev:'media' },
  { id:165, cat:'Diferenciales y eje', name:'Configurar paso de diferenciales', sev:'media' },
  { id:166, cat:'Diferenciales y eje', name:'Revisión de albardones', sev:'media' },
  { id:167, cat:'Carroceria y cabina', name:'Revisar asiento de conductor', sev:'baja' },
  { id:168, cat:'Clima y refrigeracion', name:'Cambiar siroco de A/C', sev:'media' },
  { id:169, cat:'Mantenimiento general', name:'Apretar abrazaderas', sev:'media' },
  { id:170, cat:'Diferenciales y eje', name:'Revisar sensor de temperatura de eje central diferencial', sev:'media' },
  { id:171, cat:'Suspension', name:'Vibración en suspensión delantera', sev:'media' },
  { id:172, cat:'Frenos', name:'Boster delantero izq', sev:'alta' },
  { id:173, cat:'Mantenimiento general', name:'Reparar fuga de admisión', sev:'media' },
  { id:174, cat:'Clima y refrigeracion', name:'Cambiar compresor de A/C', sev:'media' },
  { id:175, cat:'Emisiones (UREA/DEF/SCR)', name:'Mantenimiento al sistema de UREA', sev:'media' },
  { id:176, cat:'Emisiones (UREA/DEF/SCR)', name:'Limpieza a sensores de oxigenación', sev:'media' },
  { id:177, cat:'Frenos', name:'Revisar códigos y sensores del sistema ABS', sev:'alta' },
  { id:178, cat:'Transmision', name:'Calibrar GI', sev:'media' },
  { id:179, cat:'Frenos', name:'Cambiar boster', sev:'alta' },
  { id:180, cat:'Frenos', name:'Acomodar matraca', sev:'alta' },
  { id:181, cat:'Carroceria y cabina', name:'Ajustar espóiler lado izq', sev:'baja' },
  { id:182, cat:'Carroceria y cabina', name:'Revisar chirrión', sev:'baja' },
  { id:183, cat:'Mantenimiento general', name:'Cambiar ligas de tapa', sev:'media' },
  { id:184, cat:'Emisiones (UREA/DEF/SCR)', name:'Sistema de UREA', sev:'media' },
  { id:185, cat:'Transmision', name:'Cambiar reten de yoyo eje trasero lado izq', sev:'media' },
  { id:186, cat:'Direccion', name:'Revisar pernos', sev:'alta' },
  { id:187, cat:'Mantenimiento general', name:'Bujes', sev:'media' },
  { id:188, cat:'Diferenciales y eje', name:'Albardones (se simbra)', sev:'media' },
  { id:189, cat:'Direccion', name:'Cambio de palanca de direccionales', sev:'alta' },
  { id:190, cat:'Carroceria y cabina', name:'(No avienta agua los chisgueteros)', sev:'baja' },
  { id:191, cat:'Emisiones (UREA/DEF/SCR)', name:'Retocar defensa', sev:'media' },
  { id:192, cat:'Motor', name:'Revisar falla (se enciende de paro de motor)', sev:'alta' },
  { id:193, cat:'Direccion', name:'Revisar componentes de quinta rueda', sev:'alta' },
  { id:194, cat:'Carroceria y cabina', name:'Ajustar estribo lado derecho', sev:'baja' },
  { id:195, cat:'Motor', name:'No arranca', sev:'alta' },
  { id:196, cat:'Transmision', name:'Falla de transmisión', sev:'alta' },
  { id:197, cat:'Direccion', name:'Revisar crucetas', sev:'alta' },
  { id:198, cat:'Electrico y luces', name:'Faros principales', sev:'media' },
  { id:199, cat:'Electrico y luces', name:'Revisión de faro', sev:'media' },
  { id:200, cat:'Electrico y luces', name:'Revisar falso en frigobar', sev:'media' },
  { id:201, cat:'Transmision', name:'Lavado de clutch', sev:'media' },
  { id:202, cat:'Transmision', name:'Sensor de transmisión', sev:'media' },
  { id:203, cat:'Sensores y diagnostico', name:'Sensor de admisión', sev:'media' },
  { id:204, cat:'Transmision', name:'Rectificar fallas VECU transmisión', sev:'alta' },
  { id:205, cat:'Frenos', name:'Revisar frenos', sev:'alta' },
  { id:206, cat:'Electrico y luces', name:'Revisar luces en general', sev:'media' },
  { id:207, cat:'Clima y refrigeracion', name:'Cambio de compresor', sev:'media' },
  { id:208, cat:'Transmision', name:'Ajuste de embrague', sev:'media' },
  { id:209, cat:'Frenos', name:'Reparación de válvula roja de aire', sev:'alta' },
  { id:210, cat:'Suspension', name:'Revisar pistones de muelles delanteras', sev:'media' },
  { id:211, cat:'Mantenimiento general', name:'Apretar tornilleria', sev:'media' },
  { id:212, cat:'Clima y refrigeracion', name:'No funciona Refri', sev:'media' },
  { id:213, cat:'Motor', name:'Revisar revoluciones', sev:'media' },
  { id:214, cat:'Clima y refrigeracion', name:'Tubo de A/C', sev:'media' },
  { id:215, cat:'Transmision', name:'Ajuste de transmisión', sev:'media' },
  { id:216, cat:'Sistema de aire', name:'Fuga de aire en tanques', sev:'alta' },
  { id:217, cat:'Electrico y luces', name:'Cambiar plafones traseros', sev:'media' },
  { id:218, cat:'Electrico y luces', name:'Bajar luz delantera derecha', sev:'media' },
  { id:219, cat:'Motor', name:'Cambiar motor de arranque', sev:'alta' },
  { id:220, cat:'Transmision', name:'Ajustar GI', sev:'media' },
  { id:221, cat:'Carroceria y cabina', name:'Ajuste de cofre', sev:'baja' },
  { id:222, cat:'Carroceria y cabina', name:'Faldones laterales', sev:'baja' },
  { id:223, cat:'Carroceria y cabina', name:'Reparación de visera', sev:'baja' },
  { id:224, cat:'Suspension', name:'Amortiguador de cofre', sev:'media' },
  { id:225, cat:'Carroceria y cabina', name:'Lodera lado derecho', sev:'baja' },
  { id:226, cat:'Suspension', name:'Revisar suspensión delantera y trasera', sev:'media' },
  { id:227, cat:'Transmision', name:'Recalibrar transmisión', sev:'media' },
  { id:228, cat:'Diferenciales y eje', name:'Revisar eje delantero', sev:'media' },
  { id:229, cat:'Suspension', name:'Cambiar bujes de los tensores', sev:'media' },
  { id:230, cat:'Direccion', name:'Cambiar pernos y muelas de la quinta', sev:'alta' },
  { id:231, cat:'Llantas', name:'Cambio de llantas de eje trasero lado derecho', sev:'alta' },
  { id:232, cat:'Sensores y diagnostico', name:'Sensor de anticongelante', sev:'media' },
  { id:233, cat:'Electrico y luces', name:'Cambiar neblinero lado izq', sev:'media' },
  { id:234, cat:'Carroceria y cabina', name:'Manguera de depósito de limpiadores', sev:'baja' },
  { id:235, cat:'Carroceria y cabina', name:'Tapa de concabo lado izq', sev:'baja' },
  { id:236, cat:'Mantenimiento general', name:'Apretar abrazaderas de sistema de admisión', sev:'media' },
  { id:237, cat:'Suspension', name:'Calibrar suspensión', sev:'media' },
  { id:238, cat:'Carroceria y cabina', name:'Cambiar tacones de cabina', sev:'baja' },
  { id:239, cat:'Suspension', name:'Cambiar bujes de tensores', sev:'media' },
  { id:240, cat:'Llantas', name:'Cambiar llantas', sev:'alta' },
  { id:241, cat:'Direccion', name:'Cambiar crucetas', sev:'alta' },
  { id:242, cat:'Emisiones (UREA/DEF/SCR)', name:'Cambio de sensor nox', sev:'media' },
  { id:243, cat:'Suspension', name:'Cambiar válvula de suspensión delantera', sev:'media' },
  { id:244, cat:'Electrico y luces', name:'Cambiar faros principales', sev:'media' },
  { id:245, cat:'Transmision', name:'Cambiar reverseros', sev:'media' },
  { id:246, cat:'Diferenciales y eje', name:'Cambiar filtro de aceite de diferencial', sev:'media' },
  { id:247, cat:'Suspension', name:'Revisar válvula niveladora de suspensión lado izq', sev:'media' },
  { id:248, cat:'Suspension', name:'Revisar manómetro de suspensión de aire', sev:'media' },
  { id:249, cat:'Suspension', name:'Revisar amortiguador trasero', sev:'media' },
  { id:250, cat:'Carroceria y cabina', name:'Estribo lado de copiloto', sev:'baja' },
  { id:251, cat:'Motor', name:'Revisar soportes de motor', sev:'media' },
  { id:252, cat:'Electrico y luces', name:'Revisar faros', sev:'media' },
  { id:253, cat:'Electrico y luces', name:'Cambiar neblineros', sev:'media' },
  { id:254, cat:'Carroceria y cabina', name:'Poner zoquetera y base lado izq', sev:'baja' },
  { id:255, cat:'Frenos', name:'Engrasado de matracas', sev:'alta' },
  { id:256, cat:'Suspension', name:'Cambio de bujes y granadas de suspensión trasera', sev:'media' },
  { id:257, cat:'Suspension', name:'Cambio de bujes de tensores', sev:'media' },
  { id:258, cat:'Electrico y luces', name:'Revisar fusibles del STOP', sev:'media' },
  { id:259, cat:'Electrico y luces', name:'Cambiar cuartos', sev:'media' },
  { id:260, cat:'Carroceria y cabina', name:'Cambiar tolvas de salpicaderas', sev:'baja' },
  { id:261, cat:'Carroceria y cabina', name:'Moldura de espejo derecho', sev:'baja' },
  { id:262, cat:'Transmision', name:'Borrar código GI', sev:'media' },
  { id:263, cat:'Sistema de aire', name:'Cambiar válvula de asiento', sev:'alta' },
];
